/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobilestore;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class ADMIN_DELETE extends javax.swing.JDialog {

    /**
     * Creates new form ADMIN_DELETE
     */
    public ADMIN_DELETE() {
        
  this.setUndecorated(true);
        initComponents();
        setSize(1920,1080);

      Connection conn=null;
     java.sql.ResultSet rs;
  try{ 
    conn=java.sql.DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected at book_place 1");
           Statement stmt=(Statement) conn.createStatement();
         String query="SELECT * FROM mobile_store.admin_update ";
          rs=stmt.executeQuery(query);
   if(rs.isBeforeFirst()){
             while(rs.next()){
             comb.addItem(rs.getString(2));
                }
        
  }}catch(Exception e){
                 System.out.println(e);       
                    }

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        joke = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DELETE PRODUCT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(870, 20, 520, 62);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PRODUCT NAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 200, 350, 50);

        comb.setBackground(new java.awt.Color(0, 0, 0));
        comb.setFont(new java.awt.Font("Century", 1, 40)); // NOI18N
        comb.setForeground(new java.awt.Color(255, 255, 255));
        comb.setBorder(new javax.swing.border.MatteBorder(null));
        comb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combActionPerformed(evt);
            }
        });
        getContentPane().add(comb);
        comb.setBounds(840, 190, 460, 61);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("YOU SELECTED:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 280, 300, 50);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/1_xDGtplbrOnaKC1ov7t23kA.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 50, 50);

        joke.setBackground(new java.awt.Color(0, 0, 0));
        joke.setFont(new java.awt.Font("Century", 0, 40)); // NOI18N
        joke.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(joke);
        joke.setBounds(840, 280, 460, 61);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 45)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(910, 390, 240, 60);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/ADMIN DELETE.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-100, -120, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combActionPerformed
       joke.setText((String) comb.getSelectedItem());
        String val=joke.getText().trim();
  
 
     
  
    }//GEN-LAST:event_combActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int l=JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE YOU WANT TO DELETE ?", "confirm",JOptionPane.YES_NO_OPTION);{
        if(l==0){  String pkg=joke.getText().toString().trim();
      boolean found=false;
        //empty feilds
        if(joke.getText().length()==0){
             JOptionPane.showMessageDialog(rootPane," PACKAGE NAME CANNOT BE EMPTY");
        }
                String validation="";
       if(joke.getText().length()!=0){
           Connection conn=null;
           ResultSet rs;
 try{
     
      conn=java.sql.DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected 000");
           Statement stmt=(Statement) conn.createStatement();
         String query="SELECT * FROM mobile_store.admin_update WHERE PRODUCT_NAME='"+pkg+"'";
          rs=stmt.executeQuery(query);
   if(rs.isBeforeFirst()){
             while(rs.next()){
             if(rs.getString(2).equalsIgnoreCase(pkg)){
                     found=true;
                           
                 }
             }
         }
    if(found==true){
        conn=java.sql.DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected at 001");
           Statement stmt1=(Statement) conn.createStatement();
      stmt1.executeUpdate("DELETE FROM mobile_store.admin_update WHERE PRODUCT_NAME='"+pkg+"'");
            JOptionPane.showMessageDialog(rootPane,"SUCESSFULLY DELETED");
            ADMIN_DASHBOARD1 ob=new ADMIN_DASHBOARD1();
              ob.show();
             setVisible(false);
              dispose();
          
    }
                  if(found==false){
                       JOptionPane.showMessageDialog(rootPane,"NO SUCH PACKAGE");
                  
                  }}catch(Exception e){
               System.out.println(e);
    }
        
       }  
            
        }
    }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         ADMIN_DASHBOARD1 ob=new ADMIN_DASHBOARD1();
              ob.show();
             setVisible(false);
              dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN_DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN_DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN_DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN_DELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_DELETE().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel joke;
    // End of variables declaration//GEN-END:variables
}
