/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobilestore;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;
public class ADMIN_LOGIN extends javax.swing.JDialog {
private static Scanner x;
    /**
     * Creates new form ADMIN_LOGIN
     */
    public ADMIN_LOGIN() {
        this.setUndecorated(true);
        initComponents();
        setSize(1920,1080);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        paTxt = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ADMIN ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 290, 270, 60);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 400, 300, 67);

        idTxt.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        getContentPane().add(idTxt);
        idTxt.setBounds(450, 290, 340, 60);

        paTxt.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        getContentPane().add(paTxt);
        paTxt.setBounds(450, 400, 340, 60);

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 50)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 510, 210, 60);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/1_xDGtplbrOnaKC1ov7t23kA.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 10, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\DBMS Proj\\dbmsprojectfinal\\Mobilestore\\Mobilestore\\src\\mobilestore\\ADMIN LOGIN.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -50, 1980, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        String id= idTxt.getText().toString();
        String pa= paTxt.getText().toString();
        boolean found=false;
        //empty fields
        if(idTxt.getText().length()==0 || paTxt.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane,"ALL THE FIELDS MUST BE FILLED");
        }
         //username and password validation      
 if(idTxt.getText().length()!=0 &&  paTxt.getText().length()!=0 && found==false){   
       
            
          ResultSet rs;
  Connection conn=null;
            try{
            //CONNECTION ESTABLISH
            conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected");
           Statement stmt=(Statement) conn.createStatement();
         String query="SELECT * FROM mobile_store.admin_login WHERE ADMIN_ID='"+id+"' AND  PASSWORD='"+pa+"'";
          rs=stmt.executeQuery(query);
   if(rs.isBeforeFirst()){
             while(rs.next()){
                 //1 -> column number of user_id and 4 -> column number of password
                 if(rs.getString(1).equalsIgnoreCase(id) && rs.getString(3).equalsIgnoreCase(pa)){
                     found=true;
                 }
             }
         }
        }catch(Exception e){
              System.out.println(e);
        } 
                 
 }
 //IF UN AND PA ARE VALIED...LOGIN
 if(found==true &&idTxt.getText().length()!=0 &&  paTxt.getText().length()!=0){
     try{
         
  JOptionPane.showMessageDialog(rootPane,"LOGGING IN......");
 ADMIN_DASHBOARD1 ob=new ADMIN_DASHBOARD1();
    ob.setVisible(true);
        ob.show();
        dispose();
       
 
     }catch(Exception e){
          JOptionPane.showMessageDialog(rootPane,"Error");
     }
     
 }
 //checking for invalied username and password
 if(found==false &&idTxt.getText().length()!=0 &&  paTxt.getText().length()!=0){
     JOptionPane.showMessageDialog(rootPane,"INCORRECT USERNAME OR PASSWORD");
 }
      
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          LOGIN ob=new LOGIN();
        ob.setVisible(true);
        ob.show();
        dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new ADMIN_LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField paTxt;
    // End of variables declaration//GEN-END:variables
}
