/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobilestore;
import java.io.*;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import java.util.regex.*;
import net.proteanit.sql.DbUtils;
public class BILLING extends javax.swing.JDialog {
int w;
int sum=0;
    /**
     * Creates new form BILLING
     */
    public BILLING() {
        
        this.setUndecorated(true);
        initComponents();
        setSize(1920,1080);
    }

    BILLING(String id, String y, String x) {
         this.setUndecorated(true);
       initComponents();
        setSize(1920,1080);
        idTxt.setText(id);
      //
                   ResultSet rs;
  Connection conn=null;
            try{
            //CONNECTION ESTABLISH
            conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected 1");
           Statement stmt=(Statement) conn.createStatement();
         String query="SELECT * FROM mobile_store.logs ";
          rs=stmt.executeQuery(query);
   if(rs.isBeforeFirst()){
             while(rs.next()){
                String a=rs.getString(4);
               w=Integer.parseInt(a);
               
               sum=sum+w;
               }
             String pric=Integer.toString(sum);
             prc.setText(pric);
         }
        }catch(Exception e){
              System.out.println(e);
        }
        
        
        
        
         //
          try { 
              java.sql.ResultSet rs1;
       Connection conn1=null;
     
       try{
        conn1=java.sql.DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected 0 ");
           Statement stmt1=(Statement) conn1.createStatement();
         String query1="SELECT * FROM mobile_store.logs";
          rs1=stmt1.executeQuery(query1);


          
            {
      bil.setModel(DbUtils.resultSetToTableModel(rs1));
       }
             
               
       }catch(Exception e) {
           System.out.println(e);
       }
 
        
}catch (Exception ex) {

    
     
 
       
               }
          
          
          
          
          
          
          //
  
            try{
            //CONNECTION ESTABLISH
            conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected 1");
           Statement stmt=(Statement) conn.createStatement();
         String query="SELECT * FROM mobile_store.user_registration WHERE CUST_ID='"+idTxt.getText().trim()+"'";
          rs=stmt.executeQuery(query);
   if(rs.isBeforeFirst()){
             while(rs.next()){
                String a=rs.getString(2);
                nam.setText(a);
                
                     String b=rs.getString(8);
                ph.setText(b);
                
                  String query1="SELECT * FROM mobile_store.billing WHERE CUST_ID='"+idTxt.getText().trim()+"'";
          rs=stmt.executeQuery(query1);    
                
             }
         }
        }catch(Exception e){
              System.out.println(e);
        }
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        prc = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        ph = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bil = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BILLING INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 560, 50);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER_ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 70, 130, 36);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRICE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(720, 310, 90, 36);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATE:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(720, 260, 110, 36);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(830, 260, 220, 40);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CUSTOMER_NAME:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(560, 140, 260, 36);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PHONE NO:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(650, 200, 160, 40);

        idTxt.setEditable(false);
        idTxt.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(idTxt);
        idTxt.setBounds(820, 70, 170, 40);

        prc.setEditable(false);
        prc.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        prc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(prc);
        prc.setBounds(830, 310, 270, 40);

        nam.setEditable(false);
        nam.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        nam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(nam);
        nam.setBounds(830, 140, 480, 40);

        ph.setEditable(false);
        ph.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        ph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ph);
        ph.setBounds(820, 200, 430, 40);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton1.setText("BUY NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 410, 403, 53);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 560, 113, 53);

        bil.setBackground(new java.awt.Color(153, 204, 255));
        bil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(bil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 540, 460);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/circuit_board_art-wallpaper-1920x1080.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -50, 1920, 1160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                ResultSet rs;
  Connection conn=null;
            try{
            //CONNECTION ESTABLISH
            conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected 2");
           Statement stmt=(Statement) conn.createStatement();
         
      stmt.executeUpdate("DELETE FROM mobile_store.logs");
        }catch(Exception e){
              System.out.println(e);
        }
        
        
        
        String id=idTxt.getText();
         PRODUCT_LOGIN ob=new PRODUCT_LOGIN(id);
        ob.setVisible(true);
        ob.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        
        //stored procedure
        Connection co=null;
        CallableStatement cs;
      //  String d=date1.toString();
        try{
            co=DriverManager.getConnection("jdbc:mysql://localhost:3306/mobile_store","root","");
            cs=co.prepareCall("{call getbill(?,?,?,?)}");
            cs.setString("uid",idTxt.getText());
            cs.setString("cname",nam.getText());
            cs.setString("phno",ph.getText());
            //cs.setString("dat",date1.getText());
            cs.setString("pri",prc.getText());
            cs.executeUpdate();
            
        }catch(SQLException ex){
           System.out.println(ex);
            //Logger.getLogger(JFrameTest.class.getName()).log(Level.SEVERE,null,ex);
        }
       JOptionPane.showMessageDialog(rootPane,"Your order has been placed successfully...Further details will be sent to your registered phone no");
        
       String zzz=prc.getText();
         
          int mmm=Integer.parseInt(zzz);
  
          //after sucessfull validation
        
                      ResultSet rs;
  Connection conn=null;
            try{
            //CONNECTION ESTABLISH
            conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected 2");
           Statement stmt=(Statement) conn.createStatement();
         
      stmt.executeUpdate("DELETE FROM mobile_store.logs");
        }catch(Exception e){
              System.out.println(e);
        }
            String id=idTxt.getText();
                       FEEDBACK ob=new FEEDBACK(id);
        ob.setVisible(true);
        ob.show();
        dispose();
          
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new BILLING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bil;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField ph;
    private javax.swing.JTextField prc;
    // End of variables declaration//GEN-END:variables
}
