/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobilestore;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahana
 */
public class FEEDBACK extends javax.swing.JDialog {

    /**
     * Creates new form FEEDBACK
     */
    public FEEDBACK() {
        
         this.setUndecorated(true);
        initComponents();
        setSize(1920,1080);
    }
    
     public FEEDBACK(String id) {
        
         this.setUndecorated(true);
        initComponents();
        setSize(1920,1080);
        uid.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 140, 175, 47);

        uid.setBackground(new java.awt.Color(153, 153, 153));
        uid.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        uid.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(uid);
        uid.setBounds(320, 140, 177, 43);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 51));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 460, 189, 63);

        txt.setBackground(new java.awt.Color(153, 255, 255));
        txt.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        getContentPane().add(txt);
        txt.setBounds(60, 260, 1220, 160);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/1_xDGtplbrOnaKC1ov7t23kA.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 153)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 50, 50);

        jTextField1.setBackground(new java.awt.Color(0, 0, 153));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 55)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 0));
        jTextField1.setText("FEEDBACK");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(540, 20, 290, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\DBMS Proj\\dbmsprojectfinal\\Mobilestore\\Mobilestore\\src\\mobilestore\\abstract-1920x1080-3d-colorful-8k-21463.jpg")); // NOI18N
        jLabel2.setLabelFor(txt);
        jLabel2.setText("EXIT");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-30, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BILLING ob=new BILLING();
        ob.setVisible(true);
        ob.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //connection establishment
        Connection conn=null;

        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/mobile_store","root","");
            PreparedStatement ps=con.prepareStatement("insert into feedback (USER_ID,opinions)values(?,?)");
            ps.setString(1,uid.getText());
            ps.setString(2,txt.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"YOUR RESPONSE HAS BEEN RECORDED");
        }catch(Exception e){
            System.out.println(e);
        }
        //
        JOptionPane.showMessageDialog(rootPane,"THANKS FOR SHOPPING WITH US");

        WELCOME ob=new WELCOME();
        ob.setVisible(true);
        ob.show();
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEEDBACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEEDBACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEEDBACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEEDBACK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new FEEDBACK().setVisible(true);
            } 
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
