/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobilestore;

import java.io.*;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import java.util.regex.*;


/**
 *
 * @author Sahana
 */
public class USER_REG extends javax.swing.JDialog {
        private static final String USERNAME="root";
private static final String PASSWORD="";
private static final String CONN_STRING="jbdc:mysql://localhost:3306/mobile_store";
PreparedStatement pat=null,pst=null;
private static Scanner x;
private static Scanner y;
//int sl=1000;
    /**
     * Creates new form USER_REG
     */
    public USER_REG() {
         this.setUndecorated(true);
        initComponents();
        setSize(1920,1080);
        
        
            
   /*java.sql.ResultSet rs6;
        try{
  Connection conn=null;
            conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
            System.out.println("Connected");
          Statement stmt6=(Statement) conn.createStatement();
            String query6="SELECT CUST_ID FROM mobile_store.user_registration";
             rs6=stmt6.executeQuery(query6);
             if(rs6.isBeforeFirst()){
             while(rs6.next()){
               int sll=Integer.parseInt( rs6.getString(1));
                 sll++;
                 sl=sll;
             }
             }
            String m=String.valueOf(sl);
             idTxt.setText(m);
    }catch(Exception e){
  
}*/
        
        
        //
    
     
           Random random = new Random();
       String generatedid = String.format("%03d", random.nextInt(1000));
       
       idTxt.setText(generatedid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        custid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        emTxt = new javax.swing.JTextField();
        unTxt = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        addTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cpa = new javax.swing.JLabel();
        pa = new javax.swing.JLabel();
        cpTxt = new javax.swing.JPasswordField();
        paTxt = new javax.swing.JPasswordField();
        m = new javax.swing.JRadioButton();
        o = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        agTxt = new javax.swing.JTextField();
        phTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        cid1 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(0, 255, 204));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton5.setText("EDIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1010, 220, 170, 40);

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN-UP / EDIT Existing Account");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 0, 550, 94);

        custid.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        custid.setForeground(new java.awt.Color(255, 255, 255));
        custid.setText("CUSTOMER ID:");
        getContentPane().add(custid);
        custid.setBounds(10, 210, 220, 40);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ADDRESS:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 480, 241, 41);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMAIL:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 570, 130, 30);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("AGE:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 330, 64, 52);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GENDER:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 270, 140, 40);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NAME:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 150, 94, 41);

        idTxt.setEditable(false);
        idTxt.setBackground(java.awt.Color.gray);
        idTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        idTxt.setForeground(new java.awt.Color(255, 255, 255));
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        getContentPane().add(idTxt);
        idTxt.setBounds(220, 210, 200, 40);

        emTxt.setBackground(java.awt.Color.gray);
        emTxt.setFont(new java.awt.Font("Century Gothic", 0, 35)); // NOI18N
        emTxt.setForeground(new java.awt.Color(255, 255, 255));
        emTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emTxtActionPerformed(evt);
            }
        });
        getContentPane().add(emTxt);
        emTxt.setBounds(220, 570, 660, 40);

        unTxt.setBackground(java.awt.Color.gray);
        unTxt.setFont(new java.awt.Font("Century Gothic", 0, 33)); // NOI18N
        unTxt.setForeground(new java.awt.Color(255, 255, 255));
        unTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unTxtActionPerformed(evt);
            }
        });
        getContentPane().add(unTxt);
        unTxt.setBounds(220, 140, 550, 50);

        gen.setEditable(false);
        gen.setBackground(java.awt.Color.gray);
        gen.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        gen.setForeground(new java.awt.Color(255, 255, 255));
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });
        getContentPane().add(gen);
        gen.setBounds(220, 270, 210, 40);

        addTxt.setBackground(java.awt.Color.gray);
        addTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        addTxt.setForeground(new java.awt.Color(255, 255, 255));
        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });
        getContentPane().add(addTxt);
        addTxt.setBounds(220, 460, 660, 90);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/1_xDGtplbrOnaKC1ov7t23kA.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 50, 50);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 45)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 255, 51));
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 570, 380, 60);

        cpa.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        cpa.setForeground(new java.awt.Color(255, 255, 255));
        cpa.setText("CONFIRM PASSWORD :");
        getContentPane().add(cpa);
        cpa.setBounds(10, 680, 330, 60);

        pa.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        pa.setForeground(new java.awt.Color(255, 255, 255));
        pa.setText("PASSWORD :");
        getContentPane().add(pa);
        pa.setBounds(10, 620, 178, 51);

        cpTxt.setBackground(java.awt.Color.gray);
        cpTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        cpTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cpTxt);
        cpTxt.setBounds(340, 690, 650, 40);

        paTxt.setBackground(java.awt.Color.gray);
        paTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        paTxt.setForeground(new java.awt.Color(255, 255, 255));
        paTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paTxtActionPerformed(evt);
            }
        });
        getContentPane().add(paTxt);
        paTxt.setBounds(220, 630, 670, 40);

        m.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(m);
        m.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setText("MALE");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        getContentPane().add(m);
        m.setBounds(450, 270, 120, 44);

        o.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(o);
        o.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        o.setForeground(new java.awt.Color(255, 255, 255));
        o.setText("OTHERS");
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });
        getContentPane().add(o);
        o.setBounds(730, 270, 142, 44);

        f.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(f);
        f.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("FEMALE");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(580, 270, 143, 44);

        agTxt.setBackground(java.awt.Color.gray);
        agTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        agTxt.setForeground(new java.awt.Color(255, 255, 255));
        agTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agTxtActionPerformed(evt);
            }
        });
        getContentPane().add(agTxt);
        agTxt.setBounds(220, 340, 260, 40);

        phTxt.setBackground(java.awt.Color.gray);
        phTxt.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        phTxt.setForeground(new java.awt.Color(255, 255, 255));
        phTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phTxtActionPerformed(evt);
            }
        });
        getContentPane().add(phTxt);
        phTxt.setBounds(220, 400, 430, 46);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PHONE:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 400, 180, 40);

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(980, 80, 220, 40);

        b1.setBackground(new java.awt.Color(0, 255, 204));
        b1.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        b1.setText("LOAD");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(1010, 150, 170, 40);

        b2.setBackground(new java.awt.Color(0, 0, 0));
        b2.setFont(new java.awt.Font("Trebuchet MS", 1, 45)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 255, 51));
        b2.setText("UPDATE");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(990, 490, 300, 60);

        cid1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        cid1.setForeground(new java.awt.Color(255, 255, 255));
        cid1.setText("CUSTOMER ID:");
        getContentPane().add(cid1);
        cid1.setBounds(10, 80, 220, 50);

        cid.setBackground(new java.awt.Color(153, 153, 153));
        cid.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        cid.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(cid);
        cid.setBounds(220, 90, 250, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/blue_tech_circles.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -60, 1930, 1130);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-340, -160, 1920, 1160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
      
    }//GEN-LAST:event_idTxtActionPerformed

    private void emTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emTxtActionPerformed

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genActionPerformed

    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTxtActionPerformed

    private void unTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   USER_LOGIN ob=new USER_LOGIN();
        ob.setVisible(true);
        ob.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id= idTxt.getText().toString();
        String em= emTxt.getText().toString();
            String ag= agTxt.getText().toString();
         String un= unTxt.getText().toString();
        String add= addTxt.getText().toString();
                String pa= paTxt.getText().toString();
                        String cp= cpTxt.getText().toString();
                        String gn= gen.getText().toString();
                        String ph=phTxt.getText().toString();
                        boolean phon=false;
                   boolean found=false;
                   boolean h=false;    
                   boolean gmail=false;
                   
        //empty fields
        if(cpTxt.getText().length()==0 || idTxt.getText().length()==0 || emTxt.getText().length()==0|| gen.getText().length()==0||  unTxt.getText().length()==0|| addTxt.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane,"ALL THE FIELDS MUST BE FILLED");
        }
        
        
      //PHONE VALIDATION
      if(isValid(ph)){
          phon=true;
      }else{
          phon=false;
               JOptionPane.showMessageDialog(rootPane,"INVALID PHONE NUMBER");
      }
       
                   
                   
      //gmail validation
      if( gen.getText().trim().length()!=0 &&cpTxt.getText().trim().length()!=0 &&paTxt.getText().trim().length()!=0 &&addTxt.getText().trim().length()!=0 &&unTxt.getText().trim().length()!=0 &&idTxt.getText().trim().length()!=0 &&emTxt.getText().trim().length()!=0&&agTxt.getText().trim().length()!=0){
      try  {
			String emailAddress = em;
			if (isGmailAddress(emailAddress)) {
				gmail=true;
			} else {
				 JOptionPane.showMessageDialog(rootPane,"INVALIED GMAIL-ID");
			}
		} catch (Exception e) {
                                     JOptionPane.showMessageDialog(rootPane,"ERROR");
		}
      }
                   
           
      
         //age validation
           
         try{ 
              int no=Integer.parseInt(agTxt.getText());
            //converting string to int
           if(agTxt.getText().length()>=3 | no>=100 ){
              
              JOptionPane.showMessageDialog(rootPane,"ENTER VALIED AGE");
          }}catch(Exception e){
               JOptionPane.showMessageDialog(rootPane,"ENTER VALIED AGE");
          }
         //
         if(cpTxt.getText().length()!=0 && idTxt.getText().length()!=0 && emTxt.getText().length()!=0 && gen.getText().length()!=0 &&  unTxt.getText().length()!=0 && addTxt.getText().length()!=0 &&!paTxt.getText().equals(cpTxt.getText())){
              JOptionPane.showMessageDialog(rootPane,"MISMATCH PASSWORD");
              h=true;
         }
         
    
         
          //checking for prestored userid  
            if(gen.getText().toString().length()!=0 &&cpTxt.getText().toString().length()!=0 &&paTxt.getText().toString().length()!=0 &&addTxt.getText().toString().length()!=0 &&unTxt.getText().toString().length()!=0 &&agTxt.getText().toString().length()!=0 &&emTxt.getText().toString().length()!=0 &&idTxt.getText().toString().length()!=0 &&idTxt.getText().length()==3 &&agTxt.getText().length()<=3 && Integer.parseInt(agTxt.getText())<=100 && h==false){
         try{
              
        String userid="";
         x=new Scanner(new File("D:\\DBMS Proj\\USER_DATA\\user_idpa.txt"));
                 x.useDelimiter("[,]");
                while(x.hasNext()&& !found){
                    userid=x.next(); 
                  if(userid.trim().equals(idTxt.getText())){
                   found=true;
                    JOptionPane.showMessageDialog(rootPane,"USER ID NOT AVAILABLE");
           }
                }
           }catch(Exception e){
           
           }
                
                //checking for prestored password
                  try{ String password="";
              y=new Scanner(new File("D:\\DBMS Proj\\USER_DATA\\user_idpa.txt"));
                 y.useDelimiter("[,]");
                while(y.hasNext()&& !found){
                    password=y.next(); 
                  if(password.trim().equals(paTxt.getText())){
                   found=true;
                  
                    JOptionPane.showMessageDialog(rootPane,"PASSWORD NOT AVAILABLE");
                  }}
         }catch(Exception e){
             
         }
               
                  //creating a file to store password and username   
           if(phon==true&&gmail==true&&found==false&&paTxt.getText().length()!=0 &&cpTxt.getText().length()!=0 && paTxt.getText().equals(cpTxt.getText())){
                 try{ 
            FileWriter writer=new FileWriter("D:\\DBMS Proj\\USER_DATA\\user_idpa.txt",true);
 writer.write(","+id);
  writer.write(pa);

writer.close();
         //storing all the input data
           FileWriter writer2=new FileWriter("D:\\DBMS Proj\\USER_DATA\\user_details.txt",true);
           writer2.write("\n");
           writer2.write(un+"\n");
           writer2.write(id+"\n");
           writer2.write(gen.getText()+"\n");
           writer2.write(ag+"\n");
           writer2.write(add+"\n");
           writer2.write(em+"\n");
           writer2.write(pa+"\n");
           writer2.close();
           
        Connection conn=null; 
              try{
            //CONNECTION ESTABLISH
            conn=DriverManager.getConnection( "jdbc:mysql://localhost/mobile_store","root","");
          System.out.println("Connected");
            Statement stmt=(Statement) conn.createStatement();
            //INSERTION 
            String namedb=un;
            String iddb=id;
            String emdb=em;
            String padb=pa;
            String addrdb=add;
             String agdb=ag;
           String gendb=gn;
         String phdb=ph;
         System.out.println("hey");
  stmt.executeUpdate("INSERT INTO mobile_store.user_registration(CUST_ID,NAME,AGE,GENDER,ADDRESS,EMAIL,PASSWORD,PHONE_NO) VALUES ('"+iddb+"','"+namedb+"','"+agdb+"','"+gendb+"','"+addrdb+"','"+emdb+"','"+padb+"','"+phdb+"')");
           System.out.println("hey2"); 
        }catch(Exception e){
              System.out.println(e);
        }
          
        
    JOptionPane.showMessageDialog(rootPane,"REMEMBER YOUR USER_ID AND PASSWORD" );   
JOptionPane.showMessageDialog(rootPane,"SUCESSFULLY REGISTERED");
USER_LOGIN ob=new USER_LOGIN();
              ob.show();
           setVisible(false);
           dispose();
}catch(Exception e){
          System.out.println("error is"+e);
         JOptionPane.showMessageDialog(rootPane,e);
          
         }
 }
 }
           
           
     
         
         
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
   String m="MALE";    
   gen.setText(m);
      
    }//GEN-LAST:event_mActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
 String f="FEMALE";    
   gen.setText(f);
         
    }//GEN-LAST:event_fActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
String o="OTHERS";    
   gen.setText(o);
    
    }//GEN-LAST:event_oActionPerformed

    private void agTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agTxtActionPerformed

    }//GEN-LAST:event_agTxtActionPerformed

    private void paTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paTxtActionPerformed

    private void phTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phTxtActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs;
      
         try{
            String sql="Select * from mobile_store.user_registration WHERE CUST_ID='"+cid.getText().trim()+"'";
            Connection conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
             pat=conn.prepareStatement(sql);
             rs=pat.executeQuery();
            if(rs.next()){
               // idTxt.setText(rs.getString("CUST_ID"));
                unTxt .setText(rs.getString("NAME"));
                 agTxt.setText(rs.getString("AGE"));
                 gen.setText(rs.getString("GENDER"));
                 emTxt.setText(rs.getString("EMAIL"));
                 addTxt.setText(rs.getString("ADDRESS"));
                 phTxt.setText(rs.getString("PHONE_NO"));
             // btndelete.setVisible(false);
            
            }//btnsave.setEnabled(false);
} catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
    }       
       
          
         
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         Connection con=null;
        PreparedStatement pst=null;
           try{
               Class.forName("com.mysql.jdbc.Driver");
            String sql="update user_registration set NAME='"+unTxt.getText()+"',AGE='"+agTxt.getText()+"',GENDER='"+gen.getText()+"',ADDRESS='"+addTxt.getText()+"',EMAIL='"+emTxt.getText()+"' where CUST_ID='"+cid.getText()+"'";
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/mobile_store","root","");
           
             pat=conn.prepareStatement(sql);
               
                pat.execute();
             
            JOptionPane.showMessageDialog(null,"updated successfully" );
        
        
   
       }
    catch(Exception e){
       JOptionPane.showMessageDialog(null,e);
       // System.out.println(e);
   } finally{
            try{
                con.close();
                pst.close();
               
            }catch(Exception e){
                
            }
        }  
           USER_LOGIN ob=new USER_LOGIN();
        ob.setVisible(true);
        ob.show();
        dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"CHOOSE EDIT OPTION ONLY IF YOU WANT TO UPDATE YOUR DETAILS");
        cid.setVisible(true);
        cid1.setVisible(true);
        b1.setVisible(true);
         b2.setVisible(true);
        idTxt.setVisible(false);
        custid.setVisible(false);
        paTxt.setVisible(false);
        pa.setVisible(false);
        cpTxt.setVisible(false);
        cpa.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cid.setVisible(false);
        cid1.setVisible(false);
        b1.setVisible(false);
         b2.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USER_REG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USER_REG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USER_REG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USER_REG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new USER_REG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addTxt;
    private javax.swing.JTextField agTxt;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cid;
    private javax.swing.JLabel cid1;
    private javax.swing.JPasswordField cpTxt;
    private javax.swing.JLabel cpa;
    private javax.swing.JLabel custid;
    private javax.swing.JTextField emTxt;
    private javax.swing.JRadioButton f;
    private javax.swing.JTextField gen;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton m;
    private javax.swing.JRadioButton o;
    private javax.swing.JLabel pa;
    private javax.swing.JPasswordField paTxt;
    private javax.swing.JTextField phTxt;
    private javax.swing.JTextField unTxt;
    // End of variables declaration//GEN-END:variables

   public static boolean isGmailAddress(String emailAddress) {
		String expression = "^[\\w.+\\-]+@gmail\\.com$";
		CharSequence inputStr = emailAddress;
		Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
		Matcher matcher = pattern.matcher(inputStr);
		return matcher.matches();
	}
     public static boolean isValid(String ph) {
         Pattern p=Pattern.compile("(0/91)?[7-9][0-9]{9}");
         Matcher m=p.matcher(ph);
         return (m.find() && m.group().equals(ph));
         
         
     }
}
