/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobilestore;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class USER_LOGIN extends javax.swing.JDialog {
private static Scanner x;
    /**
     * Creates new form USER_DASHBOARD
     */
    public USER_LOGIN() {
        this.setUndecorated(true);
        initComponents();
        setSize(1920,1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paTxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Welcome To Techspark Mobile Store");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 670, 970, 70);

        jLabel2.setBackground(new java.awt.Color(51, 0, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("USER ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 130, 230, 67);

        idTxt.setBackground(new java.awt.Color(51, 51, 51));
        idTxt.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        idTxt.setForeground(new java.awt.Color(255, 255, 255));
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        getContentPane().add(idTxt);
        idTxt.setBounds(820, 140, 350, 55);

        jLabel3.setBackground(new java.awt.Color(51, 0, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 220, 320, 67);

        paTxt.setBackground(new java.awt.Color(51, 51, 51));
        paTxt.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        paTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(paTxt);
        paTxt.setBounds(820, 230, 350, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 40)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 0));
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(930, 400, 250, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 40)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 255, 51));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 310, 340, 70);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/1_xDGtplbrOnaKC1ov7t23kA.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 10, 50, 50);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 40)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 255, 51));
        jButton4.setText("EDIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(470, 390, 260, 50);

        jTextField1.setEditable(false);
        jTextField1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("New User?Sign Up");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(790, 410, 130, 24);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobilestore/UGZtxgGoYfvEW2ppteWkti.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -50, 1920, 1180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
              LOGIN ob=new LOGIN();
        ob.setVisible(true);
        ob.show();
        dispose();
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"REFRESH YOUR PAGE BEFORE FILLING DETAILS");
        String x;
        //b1.setContentAreaFilled(false);
        //b1.setBorder(null);
        
          USER_REG ob=new USER_REG();
        ob.setVisible(true);
        ob.show();
        dispose();
         Random random = new Random();
       String generatedid = String.format("%03d", random.nextInt(1000));
       idTxt.setText(generatedid); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           //empty fields
              String id= idTxt.getText().toString();
              String pa= paTxt.getText().toString();
              boolean found=false;
        if( idTxt.getText().length()==0 ||  paTxt.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane,"ALL THE FIELDS MUST BE FILLED");
        }
        
        if(idTxt.getText().length()!=0 &&paTxt.getText().length()!=0){
            
          ResultSet rs;
  Connection conn=null;
            try{
            //CONNECTION ESTABLISH
            conn=DriverManager.getConnection( "jdbc:mysql://localhost:3306/mobile_store","root","");
          System.out.println("Connected");
           Statement stmt=(Statement) conn.createStatement();
         String query="SELECT * FROM mobile_store.user_registration WHERE CUST_ID='"+id+"' AND  PASSWORD='"+pa+"'";
          rs=stmt.executeQuery(query);
   if(rs.isBeforeFirst()){
             while(rs.next()){
                 //1 -> column number of user_id and 4 -> column number of password
                 if(rs.getString(1).equalsIgnoreCase(id) && rs.getString(7).equalsIgnoreCase(pa)){
                     found=true;
                 }
             }
         }
        }catch(Exception e){
              System.out.println(e);
        }
        }
           String validation=" ";
         if(found==true &&idTxt.getText().length()!=0 &&  paTxt.getText().length()!=0){
     try{
         
  JOptionPane.showMessageDialog(rootPane,"LOGGING IN!");

       new  PRODUCT_LOGIN(id).setVisible(true);
         setVisible(false);
           dispose();
       System.out.println("hey");
     }catch(Exception e){
          JOptionPane.showMessageDialog(rootPane,"Error");
     }
  }
        if(found==false && idTxt.getText().length()!=0 && paTxt.getText().length()!=0){
            JOptionPane.showMessageDialog(rootPane, "INVALIED USERNAME/PASSWORD");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"CHOOSE EDIT OPTION FOR EDITING YOUR ACCOUNT");
          USER_REG ob=new USER_REG();
        ob.setVisible(true);
        ob.show();
        dispose();
       // ob.custid.setVisible(false);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USER_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USER_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USER_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USER_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          
   new USER_LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField paTxt;
    // End of variables declaration//GEN-END:variables
}
